spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: jin
      password: 1234
      database: sections
      uri: mongodb://localhost:27017/sections
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/sections?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true