server:
  port: 0

spring:
  application:
    name: sections-service
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username:
      password:
      database: sections
      uri: mongodb://127.0.0.1:27017/sections
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
