spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: jin
      password: 1234
      database: sections
      uri: mongodb://localhost:27017/sections
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true